---
- name: install httpd
  yum:
  name: httpd
  state: latest
- name: start the httpd
  systemd:
  name: httpd
  state: started
  enabled: true
- name: pass httpd through firewall
  systemd:
  name: firewalld
  state: started
  enabled: true
- name: open fw port for http
  firewalld:
  service: http
  permanent: true
  immediante: true
  state: enabled
- name:
  template:
    src: index.html.j2
    dest: /var/wwww/html/index.html
  notify: restart_httpd
