---
- name: Manage user
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: include
      include_vars:
        file: private.yml
    - name: create user
      user:
        name: " {{ user_name }} "
        password: "{{ user_password | password_hash('sha512', 'AS343') }}"
        update_password: on_create
      when: user_create == 'yes'
    - name: remove the user
      user:
        name: "{{ user_name }}"
        state: absent
        remove: true
      when: user_create == 'no'
        
  
  # Run with
  # ansible-playbook --ask-vault-pass -e "user_name=joe" encrypted.yml
  
