---
- name: Delete users only in some nodes
  hosts: all
  become: true
  gather_facts: false
  tasks:
      - name: create user
        user:
             name: '{{ item }}'
             state: 'absent'
             remove: true
        loop:
           - user1
           - user2
           - user3
        when: (user1 is defined or user2 is defined or user3 is defines and (('node1' in group_names) or ('node2' in group_names))
