--- 
- name: Information about this software
  hosts: all
  gather_facts: false
  tasks:
    - name: generate file info
      copy: 
        src: datahard.txt
        dest: /root/information.txt
    - name: name of host
      lineinfile:
        path: /root/information.txt
        regex: ^HOST
        line:
        state: present
    - name: name of host
      lineinfile:
        path: /root/information.txt
        regex: ^MEMORY
        line:
        state: present
    - name: name of host
      lineinfile:
        path: /root/information.txt
        regex: ^BIOS
        line:
        state: present
    - name: name of host
      lineinfile:
        path: /root/information.txt
        regex: ^VDA_DEVICE_SIZE
        line:
        state: present
    - name: name of host
      lineinfile:
        path: /root/information.txt
        regex: ^VDB_DEVICE_SIZE
        line:
        state: present
  
